spring.application.name=restaurant-api

spring.datasource.url=jdbc:postgresql://dbvm.bass.com.eg/restaurant_db
spring.datasource.username=postgres
spring.datasource.password=BASS
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
